auto detect version and run correct one

diff --git a/bin/dump-pg b/bin/dump-pg
--- a/bin/dump-pg
+++ b/bin/dump-pg
@@ -2,8 +2,25 @@
 
 set -euxo pipefail
 
-docker-compose up -d db
-docker-compose exec db pg_dump -f /tmp/db.sql -U postgres postgres
-docker_compose_id=$(pwd | grep -oh "[^/]*$")
-docker-compose cp db:/tmp/db.sql ./
+compose_output=$(docker compose version)
 
+if [[ $compose_output == "Docker Compose version v2"* ]]; then      
+    echo "You are using the new docker compose"
+
+    docker compose up -d db
+    docker compose exec db pg_dump -f /tmp/db.sql -U postgres postgres
+    docker_compose_id=$(pwd | grep -oh "[^/]*$")
+    docker compose cp db:/tmp/db.sql ./
+
+elif [[ $compose_output == "docker: 'compose' is not a docker command." ]]; then
+    echo "You are using the old docker-compose"
+
+    docker-compose up -d db
+    docker-compose exec db pg_dump -f /tmp/db.sql -U postgres postgres
+    docker_compose_id=$(pwd | grep -oh "[^/]*$")
+    docker-compose cp db:/tmp/db.sql ./
+
+else
+    echo "neither docker-compose nor docker compose were found! failed!"
+    exit 1
+fi
diff --git a/bin/restore-pg b/bin/restore-pg
--- a/bin/restore-pg
+++ b/bin/restore-pg
@@ -4,13 +4,39 @@ set -euxo pipefail
 
 filename=${1:-db.sql}
 
-#docker cp $filename "$(docker-compose ps -q db)":/tmp/
-docker-compose stop
-docker-compose up -d db
-docker-compose cp db.sql db:/tmp/
-# give DB a chance to initialize
-sleep 3
-docker-compose exec db dropdb -U postgres postgres
-docker-compose exec db createdb -U postgres postgres
-docker-compose exec db psql -U postgres -f /tmp/$filename postgres
+compose_output=$(docker compose version)
 
+if [[ $compose_output == "Docker Compose version v2"* ]]; then      
+    echo "You are using the new docker compose"
+
+    #docker cp $filename "$(docker-compose ps -q db)":/tmp/
+    docker compose stop
+    docker compose up -d db
+
+    # give DB a chance to initialize
+    sleep 3
+
+    docker compose cp db.sql db:/tmp/
+    docker compose exec db dropdb -U postgres postgres
+    docker compose exec db createdb -U postgres postgres
+    docker compose exec db psql -U postgres -f /tmp/$filename postgres
+
+elif [[ $compose_output == "docker: 'compose' is not a docker command." ]]; then
+    echo "You are using the old docker-compose"
+
+    #docker cp $filename "$(docker-compose ps -q db)":/tmp/
+    docker-compose stop
+    docker-compose up -d db
+
+    # give DB a chance to initialize
+    sleep 3
+
+    docker-compose cp db.sql db:/tmp/
+    docker-compose exec db dropdb -U postgres postgres
+    docker-compose exec db createdb -U postgres postgres
+    docker-compose exec db psql -U postgres -f /tmp/$filename postgres
+
+else
+    echo "neither docker-compose nor docker compose were found! failed!"
+    exit 1
+fi
